export const INDIA_MAP_CONFIG = {
  cols: 76,
  rows: 86,
  activePixels: [[22, 2], [23, 2], [24, 2], [19, 3], [20, 3], [21, 3], [22, 3], [23, 3], [24, 3], [25, 3], [26, 3], [17, 4], [18, 4], [19, 4], [20, 4], [21, 4], [22, 4], [23, 4], [24, 4], [25, 4], [26, 4], [27, 4], [17, 5], [18, 5], [19, 5], [20, 5], [21, 5], [22, 5], [23, 5], [24, 5], [25, 5], [26, 5], [27, 5], [28, 5], [29, 5], [30, 5], [16, 6], [17, 6], [18, 6], [19, 6], [20, 6], [21, 6], [22, 6], [23, 6], [24, 6], [25, 6], [26, 6], [27, 6], [28, 6], [29, 6], [30, 6], [31, 6], [32, 6]] as const,
};

export interface IndiaProfilePin {
  id: string;
  name: string;
  avatarUrl: string;
  x: number;
  y: number;
  message: string;
  tag?: string;
  delay: number;
  rotation?: number;
  messagePosition?: "top-left" | "top-right" | "bottom-left" | "bottom-right" | "top" | "bottom";
}

export interface DiscoveryStep {
  id: string;
  name: string;
  avatarSeed: string;
  city: string;
  state: string;
  x: number; // percentage from left (strictly verified inside India landmass)
  y: number; // percentage from top (strictly verified inside India landmass)
  camera: {
    scale: number;
    x: number;
    y: number;
  };
  tag: string;
  message: string;
  subvalue?: string;
  messagePosition: "top-left" | "top-right" | "bottom-left" | "bottom-right";
}

export const DISCOVERY_SEQUENCE_50: DiscoveryStep[] = [
  {
    id: "delhi",
    name: "Aarav M.",
    avatarSeed: "Aarav",
    city: "Delhi",
    state: "NCR",
    x: 31,
    y: 29,
    camera: { scale: 1.65, x: 12, y: 14 },
    tag: "MRP CHECK",
    message: "Scanned this today — MRP looks correct ✓",
    subvalue: "₹120.00 • Incl. of all taxes",
    messagePosition: "top-right",
  },
  {
    id: "chandigarh",
    name: "Simran K.",
    avatarSeed: "Simran",
    city: "Chandigarh",
    state: "Punjab",
    x: 29,
    y: 23,
    camera: { scale: 1.65, x: 14, y: 18 },
    tag: "NET QUANTITY",
    message: "500 g net quantity detected ✓",
    subvalue: "Metric standard compliant",
    messagePosition: "top-right",
  },
  {
    id: "jaipur",
    name: "Devendra S.",
    avatarSeed: "Devendra",
    city: "Jaipur",
    state: "Rajasthan",
    x: 25,
    y: 34,
    camera: { scale: 1.65, x: 16, y: 10 },
    tag: "CONSUMER CARE",
    message: "Found a missing consumer care detail ⚠",
    subvalue: "Rule 6(1)(h) Non-compliance",
    messagePosition: "top-right",
  },
  {
    id: "ahmedabad",
    name: "Meera P.",
    avatarSeed: "Meera",
    city: "Ahmedabad",
    state: "Gujarat",
    x: 15,
    y: 44,
    camera: { scale: 1.65, x: 23, y: 4 },
    tag: "PACK DATE",
    message: "Checked the label before buying ✓",
    subvalue: "Date of packing: 07/2026",
    messagePosition: "top-right",
  },
  {
    id: "surat",
    name: "Harsh V.",
    avatarSeed: "Harsh",
    city: "Surat",
    state: "Gujarat",
    x: 16,
    y: 50,
    camera: { scale: 1.65, x: 22, y: 0 },
    tag: "UNIT SALE PRICE",
    message: "Unit Sale Price missing on 1kg pack ⚠",
    subvalue: "Mandatory under 2022 Rules",
    messagePosition: "top-right",
  },
  {
    id: "mumbai",
    name: "Pooja K.",
    avatarSeed: "Pooja",
    city: "Mumbai",
    state: "Maharashtra",
    x: 18,
    y: 56,
    camera: { scale: 1.65, x: 21, y: -4 },
    tag: "DUAL UNIT",
    message: "Dual units (1L / 910g) verified ✓",
    subvalue: "Compliant edible oil labeling",
    messagePosition: "top-right",
  },
  {
    id: "pune",
    name: "Aditya D.",
    avatarSeed: "Aditya",
    city: "Pune",
    state: "Maharashtra",
    x: 22,
    y: 60,
    camera: { scale: 1.65, x: 18, y: -6 },
    tag: "FONT HEIGHT",
    message: "Font size 2.2mm is below 4.0mm standard ⚠",
    subvalue: "Rule 7 PDP Letter Height",
    messagePosition: "top-right",
  },
  {
    id: "nagpur",
    name: "Sneha R.",
    avatarSeed: "Sneha",
    city: "Nagpur",
    state: "Maharashtra",
    x: 39,
    y: 50,
    camera: { scale: 1.65, x: 7, y: 0 },
    tag: "ORIGIN CHECK",
    message: "Country of origin clearly stated: India ✓",
    subvalue: "Rule 6(1)(n) Verified",
    messagePosition: "top-right",
  },
  {
    id: "bhopal",
    name: "Alok N.",
    avatarSeed: "Alok",
    city: "Bhopal",
    state: "Madhya Pradesh",
    x: 35,
    y: 44,
    camera: { scale: 1.65, x: 10, y: 4 },
    tag: "MRP AUDIT",
    message: "MRP declaration needs a closer look",
    subvalue: "Tax inclusion text missing",
    messagePosition: "top-right",
  },
  {
    id: "indore",
    name: "Kavita J.",
    avatarSeed: "Kavita",
    city: "Indore",
    state: "Madhya Pradesh",
    x: 30,
    y: 44,
    camera: { scale: 1.65, x: 13, y: 4 },
    tag: "EXPIRY CHECK",
    message: "Best before duration clearly marked ✓",
    subvalue: "12 months from packing",
    messagePosition: "top-right",
  },
  {
    id: "lucknow",
    name: "Zaid K.",
    avatarSeed: "Zaid",
    city: "Lucknow",
    state: "Uttar Pradesh",
    x: 42,
    y: 32,
    camera: { scale: 1.65, x: 5, y: 12 },
    tag: "MANUFACTURER",
    message: "Full packer address verified ✓",
    subvalue: "PIN code & identity intact",
    messagePosition: "top-left",
  },
  {
    id: "kanpur",
    name: "Ritu M.",
    avatarSeed: "Ritu",
    city: "Kanpur",
    state: "Uttar Pradesh",
    x: 41,
    y: 34,
    camera: { scale: 1.65, x: 6, y: 10 },
    tag: "CARE CONTACT",
    message: "Toll-free customer care number verified ✓",
    subvalue: "1800-11-2233 Active",
    messagePosition: "top-left",
  },
  {
    id: "varanasi",
    name: "Shivam G.",
    avatarSeed: "Shivam",
    city: "Varanasi",
    state: "Uttar Pradesh",
    x: 48,
    y: 35,
    camera: { scale: 1.65, x: 1, y: 10 },
    tag: "BARCODE",
    message: "EAN-13 barcode matched packaging ✓",
    subvalue: "8 901234 567890",
    messagePosition: "top-left",
  },
  {
    id: "patna",
    name: "Anjali T.",
    avatarSeed: "Anjali",
    city: "Patna",
    state: "Bihar",
    x: 55,
    y: 34,
    camera: { scale: 1.65, x: -3, y: 10 },
    tag: "MRP STICKER",
    message: "Smudged price sticker over original MRP ⚠",
    subvalue: "Rule 6 Alteration Warning",
    messagePosition: "top-left",
  },
  {
    id: "ranchi",
    name: "Manish S.",
    avatarSeed: "Manish",
    city: "Ranchi",
    state: "Jharkhand",
    x: 56,
    y: 42,
    camera: { scale: 1.65, x: -4, y: 5 },
    tag: "NET WEIGHT",
    message: "250 g standard metric weight verified ✓",
    subvalue: "Second Schedule compliant",
    messagePosition: "top-left",
  },
  {
    id: "kolkata",
    name: "Ananya D.",
    avatarSeed: "Ananya",
    city: "Kolkata",
    state: "West Bengal",
    x: 66,
    y: 49,
    camera: { scale: 1.65, x: -10, y: 1 },
    tag: "COMPLIANCE",
    message: "2 compliance issues found on box ⚠",
    subvalue: "No USP & small letter height",
    messagePosition: "bottom-left",
  },
  {
    id: "siliguri",
    name: "Bikash C.",
    avatarSeed: "Bikash",
    city: "Siliguri",
    state: "West Bengal",
    x: 67,
    y: 33,
    camera: { scale: 1.65, x: -11, y: 11 },
    tag: "TEA PACK",
    message: "Packaged tea net weight 100g confirmed ✓",
    subvalue: "Gross vs Net tare verified",
    messagePosition: "top-left",
  },
  {
    id: "guwahati",
    name: "Pranab B.",
    avatarSeed: "Pranab",
    city: "Guwahati",
    state: "Assam",
    x: 80,
    y: 36,
    camera: { scale: 1.65, x: -20, y: 9 },
    tag: "SPICE PACK",
    message: "All 6 mandatory declarations present ✓",
    subvalue: "Rule 6 100% Compliant",
    messagePosition: "bottom-left",
  },
  {
    id: "bhubaneswar",
    name: "Debasish P.",
    avatarSeed: "Debasish",
    city: "Bhubaneswar",
    state: "Odisha",
    x: 56,
    y: 56,
    camera: { scale: 1.65, x: -4, y: -4 },
    tag: "SEAFOOD PACK",
    message: "Net mass with drained weight stated ✓",
    subvalue: "Rule 12 declaration verified",
    messagePosition: "top-left",
  },
  {
    id: "raipur",
    name: "Tarun K.",
    avatarSeed: "Tarun",
    city: "Raipur",
    state: "Chhattisgarh",
    x: 46,
    y: 50,
    camera: { scale: 1.65, x: 3, y: 0 },
    tag: "RICE SACK",
    message: "10 kg woven sack font height 6.5mm ✓",
    subvalue: "Standard above 5.0mm req.",
    messagePosition: "top-left",
  },
  {
    id: "hyderabad",
    name: "Sravani B.",
    avatarSeed: "Sravani",
    city: "Hyderabad",
    state: "Telangana",
    x: 36,
    y: 64,
    camera: { scale: 1.65, x: 9, y: -9 },
    tag: "FMCG SCAN",
    message: "Unit Sale Price: ₹0.45/ml declared ✓",
    subvalue: "LMPC 2022 format compliant",
    messagePosition: "top-right",
  },
  {
    id: "visakhapatnam",
    name: "Naveen C.",
    avatarSeed: "Naveen",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    x: 49,
    y: 60,
    camera: { scale: 1.65, x: 1, y: -6 },
    tag: "IMPORT GOODS",
    message: "Indian importer address sticker verified ✓",
    subvalue: "Rule 6(1)(b) Importer Check",
    messagePosition: "top-left",
  },
  {
    id: "vijayawada",
    name: "Kalyan R.",
    avatarSeed: "Kalyan",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    x: 41,
    y: 68,
    camera: { scale: 1.65, x: 6, y: -12 },
    tag: "SNACK PACK",
    message: "Net quantity verified against volume ✓",
    subvalue: "Standard metric check passed",
    messagePosition: "top-right",
  },
  {
    id: "bengaluru",
    name: "Rohan S.",
    avatarSeed: "Rohan",
    city: "Bengaluru",
    state: "Karnataka",
    x: 33,
    y: 76,
    camera: { scale: 1.65, x: 11, y: -17 },
    tag: "E-COMMERCE",
    message: "Quick commerce listing matched physical label ✓",
    subvalue: "Rule 6(10) E-Com check",
    messagePosition: "top-right",
  },
  {
    id: "mysuru",
    name: "Divya N.",
    avatarSeed: "Divya",
    city: "Mysuru",
    state: "Karnataka",
    x: 30,
    y: 79,
    camera: { scale: 1.65, x: 13, y: -19 },
    tag: "SWEET PACK",
    message: "Net weight 400g compliant declaration ✓",
    subvalue: "Fresh packed date verified",
    messagePosition: "top-right",
  },
  {
    id: "mangaluru",
    name: "Gautam P.",
    avatarSeed: "Gautam",
    city: "Mangaluru",
    state: "Karnataka",
    x: 24,
    y: 75,
    camera: { scale: 1.65, x: 17, y: -16 },
    tag: "CASHEW PACK",
    message: "Consumer helpline email verified ✓",
    subvalue: "Valid support domain",
    messagePosition: "top-right",
  },
  {
    id: "chennai",
    name: "Karthik R.",
    avatarSeed: "Karthik",
    city: "Chennai",
    state: "Tamil Nadu",
    x: 40,
    y: 78,
    camera: { scale: 1.65, x: 6, y: -18 },
    tag: "HEALTH DRINK",
    message: "Unit Sale Price explicitly calculated ✓",
    subvalue: "₹0.85 per gram",
    messagePosition: "top-left",
  },
  {
    id: "coimbatore",
    name: "Priya S.",
    avatarSeed: "Priya",
    city: "Coimbatore",
    state: "Tamil Nadu",
    x: 32,
    y: 82,
    camera: { scale: 1.65, x: 12, y: -21 },
    tag: "OIL MANDATE",
    message: "Free from added color/flavor declared ✓",
    subvalue: "FSSAI & LMPC dual match",
    messagePosition: "top-right",
  },
  {
    id: "madurai",
    name: "Sundar M.",
    avatarSeed: "Sundar",
    city: "Madurai",
    state: "Tamil Nadu",
    x: 36,
    y: 85,
    camera: { scale: 1.65, x: 9, y: -23 },
    tag: "GRAIN PACK",
    message: "Standard net quantity (1kg) certified ✓",
    subvalue: "Second Schedule Metric Unit",
    messagePosition: "top-right",
  },
  {
    id: "kochi",
    name: "Jithin T.",
    avatarSeed: "Jithin",
    city: "Kochi",
    state: "Kerala",
    x: 27,
    y: 84,
    camera: { scale: 1.65, x: 15, y: -22 },
    tag: "SPICE EXPORT",
    message: "Clear month & year of packing declared ✓",
    subvalue: "PKD: 08/2026",
    messagePosition: "top-right",
  },
  {
    id: "thiruvananthapuram",
    name: "Reshma A.",
    avatarSeed: "Reshma",
    city: "Thiruvananthapuram",
    state: "Kerala",
    x: 29,
    y: 90,
    camera: { scale: 1.65, x: 14, y: -26 },
    tag: "COCONUT OIL",
    message: "Both weight (910g) & volume (1L) stated ✓",
    subvalue: "Dual unit compliance",
    messagePosition: "top-right",
  },
  {
    id: "amritsar",
    name: "Gurpreet S.",
    avatarSeed: "Gurpreet",
    city: "Amritsar",
    state: "Punjab",
    x: 24,
    y: 19,
    camera: { scale: 1.65, x: 17, y: 20 },
    tag: "FLOUR PACK",
    message: "Atta 5kg package area & fonts valid ✓",
    subvalue: "Numeral height: 4.5mm",
    messagePosition: "top-right",
  },
  {
    id: "srinagar",
    name: "Bilal A.",
    avatarSeed: "Bilal",
    city: "Srinagar",
    state: "Jammu & Kashmir",
    x: 23,
    y: 7,
    camera: { scale: 1.65, x: 18, y: 28 },
    tag: "SAFFRON BOX",
    message: "1 g dry weight precision verified ✓",
    subvalue: "Micro-weight declaration valid",
    messagePosition: "bottom-right",
  },
  {
    id: "shimla",
    name: "Deepak T.",
    avatarSeed: "Deepak",
    city: "Shimla",
    state: "Himachal Pradesh",
    x: 32,
    y: 19,
    camera: { scale: 1.65, x: 12, y: 20 },
    tag: "APPLE JUICE",
    message: "MRP ₹90 (Incl. of all taxes) ✓",
    subvalue: "USP ₹0.45/ml present",
    messagePosition: "bottom-right",
  },
  {
    id: "dehradun",
    name: "Pooja N.",
    avatarSeed: "PoojaN",
    city: "Dehradun",
    state: "Uttarakhand",
    x: 35,
    y: 22,
    camera: { scale: 1.65, x: 10, y: 18 },
    tag: "HERBAL TEA",
    message: "Packaging date format (MM/YYYY) verified ✓",
    subvalue: "08/2026",
    messagePosition: "bottom-right",
  },
  {
    id: "jodhpur",
    name: "Ratan S.",
    avatarSeed: "Ratan",
    city: "Jodhpur",
    state: "Rajasthan",
    x: 19,
    y: 34,
    camera: { scale: 1.65, x: 20, y: 10 },
    tag: "NAMKEEN PACK",
    message: "Consumer grievance postal address missing ⚠",
    subvalue: "Rule 6(1)(h) warning",
    messagePosition: "top-right",
  },
  {
    id: "udaipur",
    name: "Nidhi B.",
    avatarSeed: "Nidhi",
    city: "Udaipur",
    state: "Rajasthan",
    x: 21,
    y: 40,
    camera: { scale: 1.65, x: 19, y: 6 },
    tag: "GHEE TIN",
    message: "1 Litre / 905 g dual quantity checked ✓",
    subvalue: "Standard tin packaging",
    messagePosition: "top-right",
  },
  {
    id: "gwalior",
    name: "Vikram P.",
    avatarSeed: "VikramP",
    city: "Gwalior",
    state: "Madhya Pradesh",
    x: 35,
    y: 36,
    camera: { scale: 1.65, x: 10, y: 9 },
    tag: "BISCUIT PACK",
    message: "Package barcode verified against registry ✓",
    subvalue: "Valid GS1 GTIN code",
    messagePosition: "top-right",
  },
  {
    id: "jabalpur",
    name: "Ramesh C.",
    avatarSeed: "Ramesh",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    x: 42,
    y: 44,
    camera: { scale: 1.65, x: 5, y: 4 },
    tag: "PULSES PACK",
    message: "Net quantity 1kg correctly displayed ✓",
    subvalue: "Compliant display panel",
    messagePosition: "top-right",
  },
  {
    id: "agra",
    name: "Farhan M.",
    avatarSeed: "Farhan",
    city: "Agra",
    state: "Uttar Pradesh",
    x: 35,
    y: 33,
    camera: { scale: 1.65, x: 10, y: 11 },
    tag: "CONFECTIONERY",
    message: "Manufacturer corporate email verified ✓",
    subvalue: "support@foodcorp.in",
    messagePosition: "top-right",
  },
  {
    id: "prayagraj",
    name: "Virendra S.",
    avatarSeed: "Virendra",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    x: 45,
    y: 35,
    camera: { scale: 1.65, x: 3, y: 10 },
    tag: "HONEY JAR",
    message: "Net mass 500g and MRP format correct ✓",
    subvalue: "USP ₹0.60/g present",
    messagePosition: "top-left",
  },
  {
    id: "gaya",
    name: "Amit K.",
    avatarSeed: "Amit",
    city: "Gaya",
    state: "Bihar",
    x: 55,
    y: 37,
    camera: { scale: 1.65, x: -3, y: 8 },
    tag: "DAIRY PACK",
    message: "Pasteurized milk volume 500ml valid ✓",
    subvalue: "Standard temperature stated",
    messagePosition: "top-left",
  },
  {
    id: "jamshedpur",
    name: "Roshni D.",
    avatarSeed: "Roshni",
    city: "Jamshedpur",
    state: "Jharkhand",
    x: 59,
    y: 43,
    camera: { scale: 1.65, x: -6, y: 5 },
    tag: "STATIONERY",
    message: "Pack of 10 pens count declaration intact ✓",
    subvalue: "Numerical count verified",
    messagePosition: "top-left",
  },
  {
    id: "cuttack",
    name: "Pradeep S.",
    avatarSeed: "Pradeep",
    city: "Cuttack",
    state: "Odisha",
    x: 55,
    y: 55,
    camera: { scale: 1.65, x: -3, y: -3 },
    tag: "SOAP BOX",
    message: "Pack of 4 (Total 400g) clearly declared ✓",
    subvalue: "Multi-piece pack Rule 24",
    messagePosition: "top-left",
  },
  {
    id: "rourkela",
    name: "Animesh B.",
    avatarSeed: "Animesh",
    city: "Rourkela",
    state: "Odisha",
    x: 52,
    y: 50,
    camera: { scale: 1.65, x: -1, y: 0 },
    tag: "SALT PACK",
    message: "Iodized salt 1kg MRP ₹28.00 verified ✓",
    subvalue: "USP ₹0.028/g",
    messagePosition: "top-left",
  },
  {
    id: "warangal",
    name: "Bhanu P.",
    avatarSeed: "BhanuP",
    city: "Warangal",
    state: "Telangana",
    x: 39,
    y: 62,
    camera: { scale: 1.65, x: 7, y: -8 },
    tag: "EDIBLE SEEDS",
    message: "Clean packaging with full FSSAI declaration ✓",
    subvalue: "All 6 requirements met",
    messagePosition: "top-right",
  },
  {
    id: "hubballi",
    name: "Basavaraj K.",
    avatarSeed: "Basavaraj",
    city: "Hubballi",
    state: "Karnataka",
    x: 26,
    y: 70,
    camera: { scale: 1.65, x: 16, y: -13 },
    tag: "JAGGERY PACK",
    message: "Standard net quantity 1kg certified ✓",
    subvalue: "Second Schedule item",
    messagePosition: "top-right",
  },
  {
    id: "shillong",
    name: "Wanbha L.",
    avatarSeed: "Wanbha",
    city: "Shillong",
    state: "Meghalaya",
    x: 80,
    y: 39,
    camera: { scale: 1.65, x: -20, y: 7 },
    tag: "ORGANIC HONEY",
    message: "Wild honey jar net weight 250g verified ✓",
    subvalue: "Local apiary verified",
    messagePosition: "bottom-left",
  },
  {
    id: "kozhikode",
    name: "Faisal M.",
    avatarSeed: "Faisal",
    city: "Kozhikode",
    state: "Kerala",
    x: 26,
    y: 80,
    camera: { scale: 1.65, x: 16, y: -20 },
    tag: "BANANA CHIPS",
    message: "Oil composition & net weight 200g checked ✓",
    subvalue: "Rule 6(1)(e) Compliant",
    messagePosition: "top-right",
  },
  {
    id: "goa",
    name: "Nathan F.",
    avatarSeed: "Nathan",
    city: "Panaji",
    state: "Goa",
    x: 20,
    y: 72,
    camera: { scale: 1.65, x: 20, y: -14 },
    tag: "BEVERAGE CAN",
    message: "Sparkling water 330ml volume certified ✓",
    subvalue: "Max retail price valid",
    messagePosition: "top-right",
  },
];

export const INDIA_COMMUNITY_PINS: IndiaProfilePin[] = DISCOVERY_SEQUENCE_50.slice(0, 6).map((s, idx) => ({
  id: s.id,
  name: s.name,
  avatarUrl: `https://api.dicebear.com/9.x/lorelei/svg?seed=${s.avatarSeed}&size=256&backgroundColor=27272a`,
  x: s.x,
  y: s.y,
  message: s.message,
  tag: s.tag,
  delay: idx * 0.3,
  rotation: idx % 2 === 0 ? -1 : 1,
  messagePosition: s.messagePosition,
}));
